kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: website-build
  labels:
    app: website
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/humensch/m210_buildconfig_site.git"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:latest
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: "website:latest"
  triggers:
    - type: GitHub
      github:
        secret: "timon"
    - type: ConfigChange
    - type: ImageChange
